### PR TITLE
Modify to work with OWMM

### PR DESCRIPTION
**Pull request by MegaPiggy**
I switched it to use arguments instead of config file. Makes it easier to use with OWMM.

### CODE REVIEW

**Comment by loco-choco** [comment]
Nice! Everything looks good!

**Comment by MegaPiggy** [comment]
If you could release this version, that'd be great.

**Comment by loco-choco** [comment]
Sorry for the delay, but I will, just give me another 30 min

**Comment by loco-choco** [comment]
Okay, I'm now seeing it and it seems you just deleted the part that moves the winhttp.dll and the doorstop.ini, what is your plan? because we need to modify those unless the alpha is really going to be downloaded from the manager

**Comment by loco-choco** [comment]
I'm going to re-add it, but using an optional argument to not break things

**Comment by loco-choco** [comment]
Can't OWMM edit the configs? but anyway I think like this it should work. Will be releasing it now after some commits

**Comment by loco-choco** [comment]
Ah okay, now I understand where you where going with this changes, basically both the game and BepInEx will be on the same folder, so no need to modify and copy the doorstop and winhttp files, so the idea will be that, if you don't specify the bepInExFolder that part of the code won't run

**Pull request merged**
